kind: pipeline
type: docker
name: build-and-push

steps:
  - name: docker-build-push
    image: plugins/docker
    settings:
      registry: ccr.ccs.tencentyun.com  # 腾讯云 Docker Registry 地址
      repo: ccr.ccs.tencentyun.com/llussy/nginx  # 替换为你的仓库地址
      username:
        from_secret: registry_user  # 从 Secrets 中获取 registry_user
      password:
        from_secret: registry_password  # 从 Secrets 中获取 registry_password
      context: .  # Dockerfile 路径相对于工作空间
      dockerfile: ./Dockerfile  # Dockerfile 文件路径
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:7}  # 使用提交哈希作为标签

trigger:
  event:
    - push
    - tag
