kind: pipeline
type: docker
name: build-and-push

steps:
  - name: docker-build-push
    image: plugins/docker
    settings:
      registry: ccr.ccs.tencentyun.com
      repo: ccr.ccs.tencentyun.com/llussy/nginx
      username:
        from_secret: registry_user
      password:
        from_secret: registry_password
      context: .
      dockerfile: ./Dockerfile
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:7}

  - name: notify-wechat-robot
    image: ccr.ccs.tencentyun.com/llussy/curl:latest
    environment:
      WECHAT_ROBOT_KEY:
        from_secret: wechat_robot_key
    commands:
      - "echo 检查环境变量: WECHAT_ROBOT_KEY=$${WECHAT_ROBOT_KEY}"
      - >
        curl -X POST "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=$${WECHAT_ROBOT_KEY}"
        -H "Content-Type: application/json"
        -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"✅ 镜像已推送成功\n仓库: ccr.ccs.tencentyun.com/llussy/nginx\nTag: $${DRONE_COMMIT_SHA:0:7}\n提交人: $${DRONE_COMMIT_AUTHOR}\n提交信息: $${DRONE_COMMIT_MESSAGE}\"}}"

trigger:
  event:
    - push
    - tag
